### ISSUE TITLE
New Release version with the latest closed PR`s

### ISSUE THREAD

**Issue by mihairadulescu** [propelorm/Propel#1043]
Hi guys, i saw that master has closed pr`s that were not released under a new minor version.
Because of that we need to use this "dev-master#3f7a284906ce3e402bcb101938270842fdad71fa".
Can we add a new release ? with the latest stuff in dev-master?

**Comment by marcj** [comment]
I don't think we release new version of v1.

**Comment by mihairadulescu** [comment]
Yes but you have closed pr`s after the latest release.... TO get those in we need to add propel in composer with hash... not with version that is silly .
