### ISSUE TITLE
Notice: Trying to access array offset on value of type bool in .../runtime/lib/Propel.php on line 739

### ISSUE THREAD

**Issue by klemens-u** [propelorm/Propel#1090]
Hi, I'm updating a symfony1 app to the latest FriendsOfSymfony + Propel versions (1.7.2)

I get the following error: 

> Notice: Trying to access array offset on value of type bool in .../runtime/lib/Propel.php on line 739

This line belongs to method processDriverOptions($source, &$write_to)

$source is

> array (size=1)
>   'ATTR_PERSISTENT' => boolean true

The code expects $source, where my example is boolean, to be an array with a key "value".

> $value = $optiondata['value'];

Any ideas? Thanks!

**Comment by mentalstring** [comment]
If you are using `databases.yml`, this is how I've been setting that type of attribute:

```
all:
  propel:
    class:          sfPropelDatabase
    param:
      classname:    PropelPDO
      # ...
      persistent:
        value:      true
      options:
        MYSQL_ATTR_MULTI_STATEMENTS:
          value:    false
```

**Comment by klemens-u** [comment]
Thanks, that resolved it.
