### ISSUE TITLE
groups for _or() in Queries

### ISSUE THREAD

**Issue by gossi** [propelorm/Propel#120]
Lets assume this one:

```
MyQuery::create()
    ->filterByA()
    ->filterByB()
    ->filterByC()
    ->_or()
    ->filterByD()
    ->_or()
    ->filterByE()
    ->find()
```

Results in:

```
A && B && ((C OR D) OR E)
```

But what I wanted and thought I get was:

```
(A && B && C) OR D OR E
```

Well, cheecky by me. But in order to do so, I would love to have something like:

```
MyQuery::create()
    ->group()
        ->filterByA()
        ->filterByB()
        ->filterByC()
    ->endGroup()
    ->_or()
    ->filterByD()
    ->_or()
    ->filterByE()
    ->find()
```

Similar to use() and endUse() and group() may be bad, since queries understand groupBy.

Would be awesome :)

**Comment by motin** [comment]
The most recent discussion on this topic is held in https://github.com/propelorm/Propel2/issues/613
