### ISSUE TITLE
propel-gen diff causes fatal error on missing constraints

### ISSUE THREAD

**Issue by rvolk** [propelorm/Propel#15]
Hi folks,
i got a fatal error while running a diff over my mysql database:

``` php
PHP Fatal error:  Call to a member function getColumn() on a non-object in /usr/local/zend/share/pear/data/propel_generator/lib/reverse/mysql/MysqlSchemaParser.php on line 301
```

I analysed this part and found out, that one of my "old" tables in this database have an InnoDB constraint to a non existing even older table. 

e.g.

``` sql
CREATE TABLE `old_table` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `fg_id` int(11) NOT NULL,
  `some_integer` int(11) NOT NULL,
  `some_decimal` decimal(3,2) NOT NULL DEFAULT '1.00',
  PRIMARY KEY (`id`),
  KEY `key1` (`integer`),
  KEY `key2` (`fg_id`),
  CONSTRAINT `con1` FOREIGN KEY (`fg_id`) REFERENCES `deleted_old_table` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `con2` FOREIGN KEY (`some_integer`) REFERENCES `some_other_table` (`ID`) ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=3163 DEFAULT CHARSET=utf8;
```

Anyhow, this table still exists from an older version of my application and doesn't ever exists in the schema.xml. 

Finally i fixed my schema manually, but only because the propel-gen diff couldn't handle it probably. I hope you are interested in this kind of use case!

Greetings,
rvolk

**Comment by fenric** [comment]
У меня была такая ошибка из-за синтаксической ошибки в XML файле схемы базы данных. Исправил ошибку, исчезла ошибка. Включайте логирование ошибок, пользуйтесь трассировкой при отладке, и будет вам счастье.
