### ISSUE TITLE
Cannot have multiple aggregate_column behaviours on same table

### ISSUE THREAD

**Issue by davidjmemmett** [propelorm/Propel#222]
Currently, if you have multiple aggregate_column behaviours on the same table, it listens only to the last behaviour specified.

See GIST https://gist.github.com/1448004 for schema.xml and actual/expected migrations.

Others have also reported the same issue on the last issue tracker, but this seems to have been lost from the public. See:
http://groups.google.com/group/propel-users/browse_thread/thread/98cba16ec353bf4a/822f3fe78c844418?lnk=gst&q=aggregate#822f3fe78c844418
http://www.propelorm.org/ticket/1055 

(Tagging behavior for USA users searching for this issue)

**Comment by peter17** [comment]
@cuevae: it is not working for me with Propel-1.7.1; it is also not compatible with generator/resources/xsd/database.xsd
