### ISSUE TITLE
preSave() and other hooks may be called several times

### ISSUE THREAD

**Issue by fzaninotto** [propelorm/Propel#321]
Here is the use case:
- create a test Author::preSave() method
- create a new Author
- create a new Book
- attach the new Book to the new Author
- persist the author using save()

Voilà: `Author::preSave()` is called twice. Here is why:
1. Author.save() calls Author::preSave() first.
2. Then, Author::save() calls Author::doSave();
3. Author::doSave() sets Author::$alreadyInSave to true and persists the author
4. Author::doSave() calls Book::save() on the related book
5. Book::save() calls Book::doSave();
6. Book::doSave() sets Book::$alreadyInSave to true and persists the Book
7. Book::doSave() calls Author::save() on the related Author (yes, the same as the first one)
8. Author::save() calls Author::preSave() **it's the second time**
9. Author::save() calls Author::doSave()
10. Author::doSave() returns prematurely because Author::$alreadyInSave is true
    11: Author::save() returns
    12 Book::doSave() sets Book::$alreadyInSave to false and returns
11. Book::save() returns
12. Author::doSave() sets Author::$alreadyInSave to false and returns
13. Author::save() returns

Conclusion: Every implementation of `preSave()` should check for `$this->isAlreadyInSave` to avoid being executed twice, and this is documented nowhere.

Possible resolutions: 
- move the `$this->isAlreadyInSave = true` up from `doSave()` to `save()`
- instead of calling `save()`on related objects, call `doSave()` (bad idea: it completely bypasses pre and post hooks).
- any other idea ?

I think this is a pretty serious bug.

**Comment by Xfaider48** [comment]
This issue still not fixed? (Up)
