### ISSUE TITLE
Class table inheritance

### ISSUE THREAD

**Issue by guilhermeaiolfi** [propelorm/Propel#40]
Hi,

currently Propel has 2 types of inheritances: single table and concrete.

But the most common inheritance and the one I would like to use is the inheritance that uses join in its children tables.

E.g:

User { id, name } //parent
Company { user_id,  slogan } //child
Person { user_id, sex } //child

That's the normalized version of the schema. It similar to the concrete table, but it won't copy all the parent's field to its children nor the parent fields to its children. Instead it will "join" those tables to access the data.

I had already talked about it in the IRC with others (Jarda mostly) and it seems that it's not just me that want that. Francois didn't really understand what I was asking when we talked, I think I didn't know how to explain it because it is recommended approach in most of the cases when dealing with inheritance. 

For reference: http://www.doctrine-project.org/docs/orm/2.0/en/reference/inheritance-mapping.html#class-table-inheritance

**Comment by miklcct** [comment]
DelegateBehavior cannot perform proper PHP inheritance in the generated classes (i.e. using "instanceof" test for a child class on an object generated by a parent query). I think a proper one using PHP extends should be made.
