### ISSUE TITLE
"propel-gen reverse" should include VIEWs (for MySQL)

### ISSUE THREAD

**Issue by lathspell** [propelorm/Propel#458]
After upgrading to the latest version (1.6.7), my schema.xml does no longer include VIEWs. Before that they were created and I just had to manuall add skipSql="true" and readOnly="true" before building the models.

They should be added to the auto generated classes as building Queries for them makes absolutely sense even if they are
not writable, depending on the database.

The generation can be re-enabled with the following patch (the github viewer corrupts it, but you get the point):

--- /home/chammers/MysqlSchemaParser.php        2012-08-29 15:36:36.000000000 +0200
+++ MysqlSchemaParser.php       2012-08-29 15:30:15.000000000 +0200
@@ -100,7 +100,7 @@
             $name = $row[0];
             $type = $row[1];
- \-            if ($name == $this->getMigrationTable() || $type != "BASE TABLE") {
- \+           if ($name == $this->getMigrationTable() || !in_array($type, array("BASE TABLE", "VIEW"))) {
               continue;
           }

As said, it would be convenient if the skipSql="true" and readOnly="true" attributes would be added. At least that would made it safe to generate VIEWs until somebody enhances the code to acutally do a CREATE VIEW instead of CREATE TABLE.

**Comment by motin** [comment]
Here is a workaround that you can use to include views in your own projects: https://gist.github.com/motin/a44281d6c916ab343ece
