### ISSUE TITLE
Migrations cannot support mlutiple schemas

### ISSUE THREAD

**Issue by willdurand** [propelorm/Propel#6]
The new 1.6 migrations cannot support multiple schemas. If you have 2 schemas:

schema1:

``` xml
<database package="beta" name="scratch" schema="beta" defaultIdMethod="native">
  <table name="projects" phpName="Projects">
...
```

schema2:

``` xml
<database package="analysisdbv2" name="scratch" schema="analysisdbv2" defaultIdMethod="native">
  <table name="analyzer_log" phpName="AnalyzerLog">
...
```

The diff task generates:

```
DROP TABLE IF EXISTS `analyzer_log`;
(snip)
CREATE TABLE `beta`.`projects`
(snip)
CREATE TABLE `analysisdbv2`.`analyzer_log`
```

---

_Imported from: http://www.propelorm.org/ticket/1483_

**Comment by FernandoFigueroa** [comment]
Hi all, i have the same problem:

SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS fos_user_group;
RENAME TABLE fos_user TO master.fos_user;
RENAME TABLE fos_group TO master.fos_group;

And so on, is there any workaround for this issue (Using other tools e.g)?? I have symfony 2.6.11 and propel-bundle 1.4.5
