### ISSUE TITLE
[phingcall] Unable to find adapter for datasource

### ISSUE THREAD

**Issue by rafa8626** [propelorm/Propel#725]
When running propel-gen diff, you'll find that the program is complaining about missing adapter to initiate DB connection. 

This happens because during that operation, self::configuration is NULL, but I don't know where is the place where is being set during the migration operation.

**Comment by tchalvak** [comment]
+1

**Comment by Yoann-TYT** [comment]
+1

**Comment by tdondich** [comment]
Will this ever be merged into a 1.x release?

**Comment by saatchimatt** [comment]
+1

**Comment by ron666** [comment]
Any updates on this?

**Comment by nibsirahsieu** [comment]
already on master branch https://github.com/propelorm/Propel/blob/master/runtime/lib/Propel.php#L651
