### ISSUE TITLE
Why is the Soft Delete behavior deprecated?

### ISSUE THREAD

**Issue by NobleUplift** [propelorm/Propel#810]
The Soft Delete behavior (http://propelorm.org/Propel/behaviors/soft-delete) is marked as deprecated "due to limitations that can't be fixed". What are those limitations? I tried to search this repository for information on soft delete, but could not find the smoking gun.

The Soft Delete behavior is almost exactly the functionality that I am looking for, whereas Archivable is the exact opposite of what I want (actually used a system with 3-4 levels of archive tables years ago. It was just a headache making sure data wasn't lost. It was).

**Comment by motin** [comment]
I was also wondering basically the same thing: Why is Soft Delete not available for Propel 2? A google search lead to http://stackoverflow.com/questions/2519297/does-propel-know-when-an-object-has-been-soft-deleted-so-that-child-entities-co which lead to http://propelorm.org/blog/2011/08/29/introducing-archivable-behavior-and-why-soft-delete-is-deprecated.html

**Comment by motin** [comment]
With the link to that blog post, this issue surely can be closed?

**Comment by marcj** [comment]
Yes thanks :)

**Comment by oojacoboo** [comment]
FWIW I created a Propel2 soft_delete behavior.

https://github.com/rentpost/propel2-soft-delete-behavior
