### ISSUE TITLE
update() requires filtering by the column being updated

### ISSUE THREAD

**Issue by guitarman0831** [propelorm/Propel#923]
When calling the `update()` function, it requires you to filter by the column being updated.

i.e. if I run the query `SampleQuery::create()->filterById($id)->update(array("Information" => "New information"));`, it returns 1, indicating a row was updated. However, checking the database information, nothing was actually updated. The Information column still contains "Old information" (the previous value).

In order to make the above query work, it would have to be ran as `SampleQuery::create()->filterByInformation("Old information")->update(array("Information" => "New information"))`, which doesn't make sense.

**Comment by nibsirahsieu** [comment]
Hi @guitarman0831 , which version did you use? i tried againts the master branch, and i can't produce the issue, here is the test case #941

**Comment by guitarman0831** [comment]
2.0.0-dev

**Comment by marcj** [comment]
Wrong repo. Correct: https://github.com/propelorm/Propel2.
