### ISSUE TITLE
Is the Propel Users group still active?

### ISSUE THREAD

**Issue by CharlesWiltgen** [propelorm/Propel#967]
Hello,

I'm a new Propel 2 user that could use some occasional help, but the Propel Users Google Group referenced on the site doesn't seem to be active. (My question from a couple weeks ago hasn't shown up, etc. The Developer group doesn't seem to be active.)

Is there an active Propel 2 user community where I can ask questions now, and hopefully contribute to someday?

— Charles

**Comment by marcj** [comment]
Well, propel v1 isn't very active and the mailing list in general neither, but you can try the new hipster stuff https://gitter.im/propelorm/Propel, which is active
