### ISSUE TITLE
Params in DocBlock of BaseObject::postHydrate incorrect

### ISSUE THREAD

**Issue by standaniels** [propelorm/Propel#968]
See https://github.com/propelorm/Propel/blob/1.7.1/runtime/lib/om/BaseObject.php#L241.

The param described in de DocBlock is `PropelPDO $con`, but the method takes the params `$row`, `$startcol` and `$rehydrate`.

**Comment by staabm** [comment]
@standaniels would you mind sending a PR?

**Comment by standaniels** [comment]
I guess I could, but I'm not entirely sure how to describe the parameters. But I could add the correct parameters though, if that would help?
