### ISSUE TITLE
Reserved keyword in table name.

### ISSUE THREAD

**Issue by dlasserre** [propelorm/Propel#974]
Hello,

I use the latest version of propel and i have a same error, please check your getting started :

<?php
$user = new User();
$user->setName('John Doe');
$group = new Group();
$group->setName('Anonymous');
// relate $user and $group
$user->addGroup($group);
// save the $user object, the $group object, and a new instance of the UserGroup class
$user->save();
?>

Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'group (id, name) VALUES (NULL, 'Anonymous')' at line 1' in /var/www/html/api/vendor/propel/propel/src/Propel/Runtime/Adapter/Pdo/PdoStatement.php:57 Stack trace: #0 /var/www/html/api/vendor/propel/propel/src/Propel/Runtime/Adapter/Pdo/PdoStatement.php(57): PDOStatement->execute(NULL) #1 /var/www/html/api/vendor/propel/propel/src/Propel/Runtime/Connection/StatementWrapper.php(194): Propel\Runtime\Adapter\Pdo\PdoStatement->execute(NULL) #2 /var/www/html/api/generated-classes/Base/Group.php(713): Propel\Runtime\Connection\StatementWrapper->execute() #3 /var/www/html/api/generated-classes/Base/Group.php(608): Base\Group->doInsert(Object(Propel\Runtime\Connection\ConnectionWrapper)) #4 /var/www/html/api/generated-classes/Base/Group.php(572): Base\Group->doSave(Object(Propel\Runti in /var/www/html/api/generated-classes/Base/Group.php on line 716

**Comment by sh0dow** [comment]
As workaround you can set name of table to 'Groups' and add attribute phpName="Group" to table tag in schema.xml. Worked for me.

**Comment by staabm** [comment]
Or activate `identifierQuoting` see http://propelorm.org/Propel/reference/buildtime-configuration.html

**Comment by dlasserre** [comment]
Perfect ! Thanks for your time !
