### ISSUE TITLE
Support collate for MySQL

### ISSUE THREAD

**Issue by lyquocphong** [propelorm/Propel#982]
Hi !

I have problem with case sensitive string comparison. I have try utf8_unicode_cs but Propel thrown error  unknown collation. I want ask about the list of Collate support for MySQL

**Comment by staabm** [comment]
hi!

whats the stacktrace of your error? AFAIR we dont have a whiteliste for collations or something like that.

**Comment by marcj** [comment]
It's an error from MySQL, because MySQL doesn't have case-sensitive Unicode collations. If you need case sensitive you need to use `utf8_bin` for example.
