### ISSUE TITLE
Docs for Versionable behaviour need updating

### ISSUE THREAD

**Issue by halfer** [propelorm/Propel#995]
The [docs here](http://propelorm.org/Propel/behaviors/versionable.html) for Propel 1 need a couple of adjustments:
- The XML snippet in the Basic Usage section is mangled
- There's a mistake in the Conditional Versioning section, in which `$con` is not used:
  
  ```
  class Book extends BaseBook
  {
    public function isVersioningNecessary($con = null)
    {
      return $this->getISBN() !== null && parent::isVersioningNecessary();
    }
  }
  ```
  
  I think this should be (`$con` added):
  
  ```
  class Book extends BaseBook
  {
    public function isVersioningNecessary($con = null)
    {
      return $this->getISBN() !== null && parent::isVersioningNecessary($con);
    }
  }
  ```

Is there a repo for Propel 1 docs? I think [this repo](https://github.com/propelorm/propelorm.github.com/blob/master/documentation/behaviors/versionable.markdown) is for Propel 2; the two issues are fixed there [and in these docs](http://propelorm.org/documentation/behaviors/versionable.html).

If someone can tell me what I need to fork, and if PRs are still being accepted for Propel 1, I will raise one.

**Comment by emiliomg** [comment]
I think you are looking for [this](https://github.com/propelorm/Propel/edit/gh-pages/behaviors/versionable.markdown). You get there by going to the behavior's [documentation](http://propelorm.org/Propel/behaviors/versionable.html) and scrolling down. At the bottom is the link for forking the documentation.

**Comment by halfer** [comment]
Thanks @emiliomg, I'll give that a try later this week.
